import networkx as nx

def graph_reader(filename: str):

    """Reads the .txt file which is generated by GENREG from Markus Meringer and returns a list containing the regular NetworkX graphs 

    Args:
        filename (string): path of the .txt file
    """
    
    regular_graphs = []
    with open(filename, 'r') as f:
        adj_list = []
        for line in f:
            if line.startswith('Graph'):
                if adj_list:
                    G = nx.parse_adjlist(adj_list, nodetype=int)
                    regular_graphs.append(G)
                    adj_list = []
                continue
            if not line.rstrip():
                continue
            adj_list.append(line.replace(' :', '').rstrip())
        G = nx.parse_adjlist(adj_list, nodetype=int)
        regular_graphs.append(G)
    return regular_graphs
